project_id = "cvbhzvmtqzifzovrofut"

[functions.generate-pix]
verify_jwt = false

[functions.webhook-mercadopago]
verify_jwt = false

[functions.discord-bot-api]
verify_jwt = false

[functions.discord-channels]
verify_jwt = false
